// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @hypermq/message
const encoding0 = {
  preencode(state, m) {
    c.string.preencode(state, m.topic)
    c.buffer.preencode(state, m.data)
    c.uint.preencode(state, m.timestamp)
    c.fixed32.preencode(state, m.key)
    state.end++ // max flag is 4 so always one byte

    if (m.consumer) c.fixed32.preencode(state, m.consumer)
    if (m.concurrent) c.uint.preencode(state, m.concurrent)
    if (m.state) c.buffer.preencode(state, m.state)
  },
  encode(state, m) {
    const flags = (m.consumer ? 1 : 0) | (m.concurrent ? 2 : 0) | (m.state ? 4 : 0)

    c.string.encode(state, m.topic)
    c.buffer.encode(state, m.data)
    c.uint.encode(state, m.timestamp)
    c.fixed32.encode(state, m.key)
    c.uint.encode(state, flags)

    if (m.consumer) c.fixed32.encode(state, m.consumer)
    if (m.concurrent) c.uint.encode(state, m.concurrent)
    if (m.state) c.buffer.encode(state, m.state)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.fixed32.decode(state)
    const flags = c.uint.decode(state)

    return {
      topic: r0,
      data: r1,
      timestamp: r2,
      key: r3,
      consumer: (flags & 1) !== 0 ? c.fixed32.decode(state) : null,
      concurrent: (flags & 2) !== 0 ? c.uint.decode(state) : 0,
      state: (flags & 4) !== 0 ? c.buffer.decode(state) : null
    }
  }
}

// @hypermq/action
const encoding1 = {
  preencode(state, m) {
    c.fixed32.preencode(state, m.key)
    c.fixed32.preencode(state, m.consumer)
  },
  encode(state, m) {
    c.fixed32.encode(state, m.key)
    c.fixed32.encode(state, m.consumer)
  },
  decode(state) {
    const r0 = c.fixed32.decode(state)
    const r1 = c.fixed32.decode(state)

    return {
      key: r0,
      consumer: r1
    }
  }
}

// @hypermq/register
const encoding2 = {
  preencode(state, m) {
    c.fixed32.preencode(state, m.key)
    state.end++ // flags are fixed size
  },
  encode(state, m) {
    const flags = m.producer ? 1 : 0

    c.fixed32.encode(state, m.key)
    c.uint8.encode(state, flags)
  },
  decode(state) {
    const r0 = c.fixed32.decode(state)
    const flags = c.uint8.decode(state)

    return {
      key: r0,
      producer: (flags & 1) !== 0
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@hypermq/message':
      return encoding0
    case '@hypermq/action':
      return encoding1
    case '@hypermq/register':
      return encoding2
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
